site_name: tigPesa Official API Documentation
pages:
- Home:    index.md
- About:   about.md
- Customer To Business:     b2b.md
- Business To Customer:     b2b.md
- Payments:     payments.md
theme: readthedocs
