site_name: tigPesa Official API Documentation
pages:
- Home:                      index.md
- About:                     about.md
- Online Payments Guide:     online_payments.md
- Partner Integration Guide: partner_integration.md
theme: readthedocs
